/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

import java.awt.*;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.*;
import se.chalmers.ait.dat215.lab2.Recipe;

/**
 *
 * @author Shif
 */
public class RecipePanelTest extends javax.swing.JPanel {
    
    private final Recipe recipe;
    private final ImageIcon imageIcon;

    /**
     * Creates new form RecipePanelTest
     */
    public RecipePanelTest(Recipe recipe) {
        this.recipe = recipe;
        initComponents();
        imageIcon = recipe.getImage(10,10);
        JLabel iconLabel = new JLabel("", imageIcon, JLabel.CENTER);
        iconLabel.setIcon(imageIcon);
        //setLayout(BorderLayout.CENTER);
        this.add(iconLabel,BorderLayout.CENTER);
    }
    
    public RecipePanelTest() {
        recipe = null;
        imageIcon = null;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawRect(0, 0, this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewRecipeButton = new javax.swing.JButton();

        viewRecipeButton.setText("Se recept");
        viewRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecipeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(viewRecipeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(viewRecipeButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecipeButtonActionPerformed
        pcs.firePropertyChange(recipe.getName(), false, recipe);
    }//GEN-LAST:event_viewRecipeButtonActionPerformed

    /*@Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        imageIcon.paintIcon(this, g, 0, 0);
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton viewRecipeButton;
    // End of variables declaration//GEN-END:variables

    private final PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    
    public void addObserver(PropertyChangeListener observer) { 
        this.pcs.addPropertyChangeListener(observer);
    }
    
}
